### ISSUE TITLE
/subjects/1 に行った後にブラウザバックし、/subjects/2 をクリックすると、rerender される前の /subjects/1 の情報が一瞬見える

### ISSUE THREAD

**Issue by longtime1116** [nostaygr/ranker#115]
ので、loading... を出すようにしたい。

**Comment by aikiyy** [comment]
~~toggleで実装したみたいに、0or1を反転させて、反転した時にのみ表示するようにするとか？
あんまりいい案ではないなー

**Comment by longtime1116** [comment]
これ、Twitter かなにかでもよく似たような現象起きるので、あんまり気にすることでは無いのかな〜
みせちゃならないもの(例えば他人の非公開のitems)とかが出ているわけじゃ無いもんね。

**Comment by aikiyy** [comment]
これはそういうもの。
