### ISSUE TITLE
[バグ] http://localhost:4000/subjects/:subject_id に直接飛ぶと何も表示されない

### ISSUE THREAD

**Issue by longtime1116** [nostaygr/ranker#97]

**Comment by aikiyy** [comment]
> this.findSubjectById(parseInt(props.match.params.id))

の部分が悪さしてるね。propsとして渡すんじゃなくて、一回api叩かないとダメかも。

**Comment by longtime1116** [comment]
なんでわかったのかとか気になる！！

**Comment by aikiyy** [comment]
上のコマンドがちゃんと働くのって、Subjectsが表示されていて、そこからSubjectに移動するときだよね。
すなわち、それ以外はうまくいかないんじゃないかなって。

**Comment by longtime1116** [comment]
うーむ。
location.reload() しないようにできれば、解決しそうな気もする。のでそっちを優先的に片付けるべき？

**Comment by aikiyy** [comment]
結局url直叩きに対応できないから、バックエンド叩かせたほうがいい気がする

**Comment by longtime1116** [comment]
あ、やっと意味が分かった。

location.reload() の代わりに getItem(), getSubject() を呼び出すようにするってことね！！

**Comment by aikiyy** [comment]
挙動不安定だが、解決したのでクローズ
